<a href="https://colab.research.google.com/github/Deepanshu-Malakar/Deepanshu-Malakar/blob/main/intro_to_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)



2.4.0+cu121


In [3]:
#introduction
scalar=torch.tensor(7)
print(scalar)

tensor(7)


Properties of Scalars

In [4]:
#to get dimension of tensor
print("dimension of scalar is :",scalar.ndim)
#to get tensor back as integer
print("value of scalar is: ",scalar.item())

dimension of scalar is : 0
value of scalar is:  7


vector

In [5]:
vector=torch.tensor([7,7])
print(vector)
print("dimension of vector :",vector.ndim)
print("shape of vector : ",vector.shape)
vector2=torch.tensor([[2,4,3],
                     [4,5,3]])
print(vector2)
print("dimension of vector2 :",vector2.ndim)
print("shape of vector2 : ",vector2.shape)

tensor([7, 7])
dimension of vector : 1
shape of vector :  torch.Size([2])
tensor([[2, 4, 3],
        [4, 5, 3]])
dimension of vector2 : 2
shape of vector2 :  torch.Size([2, 3])


Random tensors


In [6]:
random_tensor = torch.rand(4,3,3)
print(random_tensor)

tensor([[[0.0287, 0.6924, 0.7679],
         [0.5430, 0.1697, 0.6355],
         [0.9395, 0.5599, 0.1460]],

        [[0.4752, 0.2467, 0.5950],
         [0.0485, 0.6666, 0.1551],
         [0.2903, 0.3194, 0.6047]],

        [[0.3578, 0.2227, 0.8046],
         [0.1079, 0.3525, 0.6358],
         [0.0199, 0.3903, 0.3667]],

        [[0.7255, 0.9801, 0.5309],
         [0.3363, 0.0554, 0.5704],
         [0.4259, 0.3452, 0.2257]]])


Image tensor

In [7]:
random_image_tensor=torch.rand(size=(224,224,3)) #height width color_channels(rgb)
print("shape: ",random_image_tensor.shape)
print("dimension: ",random_image_tensor.ndim)

shape:  torch.Size([224, 224, 3])
dimension:  3


**Zeroes and Ones**

In [8]:
zeroes=torch.zeros(3,4)
ones=torch.ones(3,4)
print(zeroes)
print("\n")
print(ones)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Creating Range of tensors

In [9]:
#use torch.arange(start,end,step)   creates an AP with a=start an=end d=step
#  doesnot include the end element
range1=torch.arange(start=1,end=21,step=2)
print(range1)
range2=torch.arange(start=5,end=32,step=4)
print(range2)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
tensor([ 5,  9, 13, 17, 21, 25, 29])


Tensors like (creating a tensor with same shape like another tensor)

In [10]:
tensor_like=torch.rand_like(input=random_tensor)
print(tensor_like)

tensor([[[0.1300, 0.7365, 0.1635],
         [0.3754, 0.9372, 0.3068],
         [0.3763, 0.5386, 0.4554]],

        [[0.6275, 0.7632, 0.1902],
         [0.8192, 0.2178, 0.0319],
         [0.6284, 0.9733, 0.2281]],

        [[0.2361, 0.6958, 0.2677],
         [0.1398, 0.3941, 0.9223],
         [0.7603, 0.9117, 0.1485]],

        [[0.2584, 0.1958, 0.1128],
         [0.7975, 0.1086, 0.0119],
         [0.5633, 0.2862, 0.6784]]])


**Getting Information from tensors**
1)Tensor Manupulation *(Tensor operations)*

In [11]:
t=torch.tensor([1,2,3,4])
print("tensor: ",t)
print("tensor + 1: ",t+1)
print("tensor - 1: ",t-1)
print("tensor * 10: ",t*10)
print("tensor / 10: ",t/10)


tensor:  tensor([1, 2, 3, 4])
tensor + 1:  tensor([2, 3, 4, 5])
tensor - 1:  tensor([0, 1, 2, 3])
tensor * 10:  tensor([10, 20, 30, 40])
tensor / 10:  tensor([0.1000, 0.2000, 0.3000, 0.4000])


Matrix Multiplication

In [5]:
#element wise matrix multiplication
tensor1=torch.tensor([1,2,3])
tensor2=torch.tensor([4,5,6])
print(f"{tensor1}*{tensor2}={tensor1*tensor2}")


tensor([1, 2, 3])*tensor([4, 5, 6])=tensor([ 4, 10, 18])


Dot product of tensors

In [7]:
print(tensor1.matmul(tensor2))
print("note that 32=4+10+18")

tensor(32)
note that 32=4+10+18


In [13]:
tensor1=torch.randint(low=0,high=5,size=(2,3))
tensor2=torch.randint(low=0,high=5,size=(3,4))
print("tensor1:")
print(tensor1)
print("tensor2:")
print(tensor2)
print(f"tensor1 x tensor2 =\n{tensor1.matmul(tensor2)}")

tensor1:
tensor([[0, 3, 3],
        [0, 3, 1]])
tensor2:
tensor([[3, 3, 3, 4],
        [0, 0, 2, 1],
        [4, 3, 4, 4]])
tensor1 x tensor2 =
tensor([[12,  9, 18, 15],
        [ 4,  3, 10,  7]])
